2022-07-04 16:19:11,615 INFO    MainThread:5408 [wandb_setup.py:_flush():76] Loading settings from /home/solrak/.config/wandb/settings
2022-07-04 16:19:11,616 INFO    MainThread:5408 [wandb_setup.py:_flush():76] Loading settings from /home/solrak/Documents/clasificador_de_sentimientos/Prototypes/Sentan-I/wandb/settings
2022-07-04 16:19:11,616 INFO    MainThread:5408 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2022-07-04 16:19:11,616 INFO    MainThread:5408 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2022-07-04 16:19:11,617 INFO    MainThread:5408 [wandb_init.py:_log_setup():428] Logging user logs to /home/solrak/Documents/clasificador_de_sentimientos/Prototypes/Sentan-I/wandb/run-20220704_161911-379b41bk/logs/debug.log
2022-07-04 16:19:11,617 INFO    MainThread:5408 [wandb_init.py:_log_setup():429] Logging internal logs to /home/solrak/Documents/clasificador_de_sentimientos/Prototypes/Sentan-I/wandb/run-20220704_161911-379b41bk/logs/debug-internal.log
2022-07-04 16:19:11,617 INFO    MainThread:5408 [wandb_init.py:_jupyter_setup():378] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x7f37bb3d1810>
2022-07-04 16:19:11,618 INFO    MainThread:5408 [wandb_init.py:init():462] calling init triggers
2022-07-04 16:19:11,618 INFO    MainThread:5408 [wandb_init.py:init():465] wandb.init called with sweep_config: {}
config: {}
2022-07-04 16:19:11,618 INFO    MainThread:5408 [wandb_init.py:init():481] re-initializing run, found existing run on stack: 38jgkpx6
2022-07-04 16:19:11,621 INFO    MainThread:5408 [wandb_run.py:_finish():1685] finishing run solrak/Clasificador de sentimientos/38jgkpx6
2022-07-04 16:19:11,622 ERROR   MainThread:5408 [jupyter.py:save_history():427] Run pip install nbformat to save notebook history
2022-07-04 16:19:11,622 INFO    MainThread:5408 [jupyter.py:save_ipynb():377] not saving jupyter notebook
2022-07-04 16:19:11,623 INFO    MainThread:5408 [wandb_init.py:_jupyter_teardown():360] cleaning up jupyter logic
2022-07-04 16:19:11,626 INFO    MainThread:5408 [wandb_init.py:init():515] starting backend
2022-07-04 16:19:11,626 INFO    MainThread:5408 [backend.py:_multiprocessing_setup():97] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2022-07-04 16:19:11,629 INFO    MainThread:5408 [backend.py:ensure_launched():217] starting backend process...
2022-07-04 16:19:11,654 INFO    MainThread:5408 [backend.py:ensure_launched():222] started backend process with pid: 7221
2022-07-04 16:19:11,655 INFO    MainThread:5408 [wandb_init.py:init():525] backend started and connected
2022-07-04 16:19:11,659 INFO    MainThread:5408 [wandb_run.py:_label_probe_notebook():1089] probe notebook
2022-07-04 16:19:11,659 INFO    MainThread:5408 [wandb_run.py:_label_probe_notebook():1099] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2022-07-04 16:19:11,659 INFO    MainThread:5408 [wandb_init.py:init():596] updated telemetry
2022-07-04 16:19:11,668 INFO    MainThread:5408 [wandb_init.py:init():627] communicating run to backend with 30 second timeout
2022-07-04 16:19:12,959 INFO    MainThread:5408 [wandb_run.py:_on_init():1924] communicating current version
2022-07-04 16:19:13,237 INFO    MainThread:5408 [wandb_run.py:_on_init():1928] got version response 
2022-07-04 16:19:13,238 INFO    MainThread:5408 [wandb_init.py:init():662] starting run threads in backend
2022-07-04 16:19:13,269 INFO    MainThread:5408 [wandb_run.py:_console_start():1898] atexit reg
2022-07-04 16:19:13,270 INFO    MainThread:5408 [wandb_run.py:_redirect():1771] redirect: SettingsConsole.WRAP
2022-07-04 16:19:13,270 INFO    MainThread:5408 [wandb_run.py:_redirect():1808] Wrapping output streams.
2022-07-04 16:19:13,271 INFO    MainThread:5408 [wandb_run.py:_redirect():1832] Redirects installed.
2022-07-04 16:19:13,272 INFO    MainThread:5408 [wandb_init.py:init():688] run started, returning control to user process
2022-07-04 16:38:58,944 INFO    MainThread:5408 [wandb_setup.py:_flush():76] Loading settings from /home/solrak/.config/wandb/settings
2022-07-04 16:38:58,944 INFO    MainThread:5408 [wandb_setup.py:_flush():76] Loading settings from /home/solrak/Documents/clasificador_de_sentimientos/Prototypes/Sentan-I/wandb/settings
2022-07-04 16:38:58,945 INFO    MainThread:5408 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2022-07-04 16:38:58,945 INFO    MainThread:5408 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2022-07-04 16:38:58,945 INFO    MainThread:5408 [wandb_init.py:_log_setup():428] Logging user logs to /home/solrak/Documents/clasificador_de_sentimientos/Prototypes/Sentan-I/wandb/run-20220704_163858-25miuycg/logs/debug.log
2022-07-04 16:38:58,946 INFO    MainThread:5408 [wandb_init.py:_log_setup():429] Logging internal logs to /home/solrak/Documents/clasificador_de_sentimientos/Prototypes/Sentan-I/wandb/run-20220704_163858-25miuycg/logs/debug-internal.log
2022-07-04 16:38:58,946 INFO    MainThread:5408 [wandb_init.py:_jupyter_setup():378] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x7f37bb3d1240>
2022-07-04 16:38:58,947 INFO    MainThread:5408 [wandb_init.py:init():462] calling init triggers
2022-07-04 16:38:58,947 INFO    MainThread:5408 [wandb_init.py:init():465] wandb.init called with sweep_config: {}
config: {}
2022-07-04 16:38:58,947 INFO    MainThread:5408 [wandb_init.py:init():481] re-initializing run, found existing run on stack: 379b41bk
2022-07-04 16:38:58,953 INFO    MainThread:5408 [wandb_run.py:_finish():1685] finishing run solrak/Clasificador de sentimientos/379b41bk
2022-07-04 16:38:58,955 ERROR   MainThread:5408 [jupyter.py:save_history():427] Run pip install nbformat to save notebook history
2022-07-04 16:38:58,955 INFO    MainThread:5408 [jupyter.py:save_ipynb():377] not saving jupyter notebook
2022-07-04 16:38:58,955 INFO    MainThread:5408 [wandb_init.py:_jupyter_teardown():360] cleaning up jupyter logic
2022-07-04 16:38:58,956 INFO    MainThread:5408 [wandb_run.py:_atexit_cleanup():1867] got exitcode: 0
2022-07-04 16:38:58,958 INFO    MainThread:5408 [wandb_run.py:_restore():1839] restore
2022-07-04 16:38:59,424 INFO    MainThread:5408 [wandb_run.py:_on_finish():1996] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 756
  total_bytes: 756
}

2022-07-04 16:39:04,524 INFO    MainThread:5408 [wandb_run.py:_on_finish():1996] got exit ret: None
2022-07-04 16:39:04,625 INFO    MainThread:5408 [wandb_run.py:_restore():1839] restore
2022-07-04 16:39:04,640 ERROR   MainThread:5408 [wandb_init.py:init():1026] error
Traceback (most recent call last):
  File "/home/solrak/Documents/clasificador_de_sentimientos/Prototypes/proto_env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1876, in _atexit_cleanup
    self._on_finish()
  File "/home/solrak/Documents/clasificador_de_sentimientos/Prototypes/proto_env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1994, in _on_finish
    self._backend.interface.communicate_poll_exit()
  File "/home/solrak/Documents/clasificador_de_sentimientos/Prototypes/proto_env/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 653, in communicate_poll_exit
    resp = self._communicate_poll_exit(poll_exit)
  File "/home/solrak/Documents/clasificador_de_sentimientos/Prototypes/proto_env/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 419, in _communicate_poll_exit
    result = self._communicate(rec)
  File "/home/solrak/Documents/clasificador_de_sentimientos/Prototypes/proto_env/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 226, in _communicate
    return self._communicate_async(rec, local=local).get(timeout=timeout)
  File "/home/solrak/Documents/clasificador_de_sentimientos/Prototypes/proto_env/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 231, in _communicate_async
    raise Exception("The wandb backend process has shutdown")
Exception: The wandb backend process has shutdown

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/solrak/Documents/clasificador_de_sentimientos/Prototypes/proto_env/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 999, in init
    run = wi.init()
  File "/home/solrak/Documents/clasificador_de_sentimientos/Prototypes/proto_env/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 494, in init
    self._wl._global_run_stack[-1].finish()
  File "/home/solrak/Documents/clasificador_de_sentimientos/Prototypes/proto_env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 256, in wrapper
    return func(self, *args, **kwargs)
  File "/home/solrak/Documents/clasificador_de_sentimientos/Prototypes/proto_env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 222, in wrapper
    return func(self, *args, **kwargs)
  File "/home/solrak/Documents/clasificador_de_sentimientos/Prototypes/proto_env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1678, in finish
    return self._finish(exit_code, quiet)
  File "/home/solrak/Documents/clasificador_de_sentimientos/Prototypes/proto_env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1691, in _finish
    self._atexit_cleanup(exit_code=exit_code)
  File "/home/solrak/Documents/clasificador_de_sentimientos/Prototypes/proto_env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1887, in _atexit_cleanup
    self._backend.cleanup()
  File "/home/solrak/Documents/clasificador_de_sentimientos/Prototypes/proto_env/lib/python3.10/site-packages/wandb/sdk/backend/backend.py", line 246, in cleanup
    self.interface.join()
  File "/home/solrak/Documents/clasificador_de_sentimientos/Prototypes/proto_env/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 475, in join
    super().join()
  File "/home/solrak/Documents/clasificador_de_sentimientos/Prototypes/proto_env/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 666, in join
    _ = self._communicate_shutdown()
  File "/home/solrak/Documents/clasificador_de_sentimientos/Prototypes/proto_env/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 472, in _communicate_shutdown
    _ = self._communicate(record)
  File "/home/solrak/Documents/clasificador_de_sentimientos/Prototypes/proto_env/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 226, in _communicate
    return self._communicate_async(rec, local=local).get(timeout=timeout)
  File "/home/solrak/Documents/clasificador_de_sentimientos/Prototypes/proto_env/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 231, in _communicate_async
    raise Exception("The wandb backend process has shutdown")
Exception: The wandb backend process has shutdown
2022-07-04 16:39:15,693 INFO    MainThread:5408 [wandb_setup.py:_flush():76] Loading settings from /home/solrak/.config/wandb/settings
2022-07-04 16:39:15,693 INFO    MainThread:5408 [wandb_setup.py:_flush():76] Loading settings from /home/solrak/Documents/clasificador_de_sentimientos/Prototypes/Sentan-I/wandb/settings
2022-07-04 16:39:15,694 INFO    MainThread:5408 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2022-07-04 16:39:15,694 INFO    MainThread:5408 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2022-07-04 16:39:15,694 INFO    MainThread:5408 [wandb_init.py:_log_setup():428] Logging user logs to /home/solrak/Documents/clasificador_de_sentimientos/Prototypes/Sentan-I/wandb/run-20220704_163915-e0jc9hsi/logs/debug.log
2022-07-04 16:39:15,695 INFO    MainThread:5408 [wandb_init.py:_log_setup():429] Logging internal logs to /home/solrak/Documents/clasificador_de_sentimientos/Prototypes/Sentan-I/wandb/run-20220704_163915-e0jc9hsi/logs/debug-internal.log
2022-07-04 16:39:15,695 INFO    MainThread:5408 [wandb_init.py:_jupyter_setup():378] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x7f37b8157d00>
2022-07-04 16:39:15,696 INFO    MainThread:5408 [wandb_init.py:init():462] calling init triggers
2022-07-04 16:39:15,697 INFO    MainThread:5408 [wandb_init.py:init():465] wandb.init called with sweep_config: {}
config: {}
2022-07-04 16:39:15,697 INFO    MainThread:5408 [wandb_init.py:init():481] re-initializing run, found existing run on stack: 379b41bk
2022-07-04 16:39:15,701 INFO    MainThread:5408 [wandb_run.py:_finish():1685] finishing run solrak/Clasificador de sentimientos/379b41bk
2022-07-04 16:39:15,703 ERROR   MainThread:5408 [jupyter.py:save_history():427] Run pip install nbformat to save notebook history
2022-07-04 16:39:15,703 INFO    MainThread:5408 [jupyter.py:save_ipynb():377] not saving jupyter notebook
2022-07-04 16:39:15,703 INFO    MainThread:5408 [wandb_init.py:_jupyter_teardown():360] cleaning up jupyter logic
